; PlatformIO Project Configuration File
; Xe Robot dieu khien bang giong noi (ESP32-S3 + INMP441)

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -Ofast
    -I lib/audio_input
    -I lib/audio_processor/src
    -I lib/audio_processor/src/kissfft
    -I lib/neural_network/src
    -Wno-unused-parameter
monitor_filters = esp32_exception_decoder
